### ISSUE TITLE
[Issue] decrement() function returning exception

### ISSUE THREAD

**Issue by SturmDrangAltaar** [laravel/cashier#359]
Hi, 

Been using what I assume are wrapper functions in cashier to increment and decrement a user's subscription count. Increment still appears to work fine, but I'm getting the following exception on decrement (partial stack trace) :

> message: Invalid non-negative integer
file: /var/www/html/vendor/stripe/stripe-php/lib/ApiRequestor.php
line: 108
trace: #0 /var/www/html/vendor/stripe/stripe-php/lib/ApiRequestor.php(259): Stripe\ApiRequestor->handleApiError('{\n  "error": {\n...', 400, Array, Array)
#1 /var/www/html/vendor/stripe/stripe-php/lib/ApiRequestor.php(65): Stripe\ApiRequestor->_interpretResponse('{\n  "error": {\n...', 400, Array)
#2 /var/www/html/vendor/stripe/stripe-php/lib/ApiResource.php(120): Stripe\ApiRequestor->request('post', '/v1/subscriptio...', Array, Array)
#3 /var/www/html/vendor/stripe/stripe-php/lib/ApiResource.php(111): Stripe\ApiResource::_staticRequest('post', '/v1/subscriptio...', Array, Object(Stripe\Util\RequestOptions))
#4 /var/www/html/vendor/stripe/stripe-php/lib/ApiResource.php(190): Stripe\ApiResource->_request('post', '/v1/subscriptio...', Array, NULL)
#5 /var/www/html/vendor/stripe/stripe-php/lib/Subscription.php(85): Stripe\ApiResource->_save(NULL)
#6 /var/www/html/vendor/laravel/cashier/src/Laravel/Cashier/Customer.php(79): Stripe\Subscription->save()
#7 /var/www/html/vendor/laravel/cashier/src/Laravel/Cashier/Customer.php(63): Laravel\Cashier\Customer->saveSubscription(Array)
#8 /var/www/html/vendor/laravel/cashier/src/Laravel/Cashier/StripeGateway.php(390): Laravel\Cashier\Customer->updateSubscription(Array)
#9 /var/www/html/vendor/laravel/cashier/src/Laravel/Cashier/StripeGateway.php(367): Laravel\Cashier\StripeGateway->updateQuantity(-1, Object(Laravel\Cashier\Customer))
#10 /var/www/html/app/Http/Controllers/AgentController.php(365): Laravel\Cashier\StripeGateway->decrement()

Decrement used to work up to about a week or 2 ago, so not sure what changed that updateQuantity() doesn't accept negative integers anymore?

Current setup:
Laravel 5.2.*
Cashier ~5.0 (Can't upgrade currently as a database migration would be required first)
PHP 5.6.28

Thanks!

**Comment by SturmDrangAltaar** [comment]
Figured this one out. It happens on accounts that are already on a 0 count, so not really an issue. I'm not sure if a fatal error is the best way to deal with this though, perhaps a warning level notice rather?

Thanks, closing issue.
